language: python
python:
  - "3.6.6"
pip:
  - "18.1"
install:
  - pip install -r requirements.txt
script: pytest -v
notifications:
  email:
    recipients:
    - task4texprog@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
